apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "15s"
          queryTimeout: "60s"
          httpMethod: "POST"
      
      - name: Zabbix
        type: alexanderzobnin-zabbix-datasource
        access: proxy
        url: http://zabbix-web/api_jsonrpc.php
        isDefault: false
        editable: true
        jsonData:
          username: Admin
          trends: true
          trendsFrom: "7d"
          trendsRange: "4d"
          cacheTTL: "1h"
        secureJsonData:
          password: zabbix
