apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
      
      - name: Zabbix
        type: alexanderzobnin-zabbix-datasource
        access: proxy
        url: http://zabbix-web.monitoring:8080/api_jsonrpc.php
        jsonData:
          username: Admin
          trends: true
          trendsFrom: "7d"
          trendsRange: "4d"
          cacheTTL: "1h"
        secureJsonData:
          password: zabbix
        editable: true
